name: build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: unzip -o armorindicator.zip -d project
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.12"
      - run: gradle build --no-daemon
        working-directory: project
      - uses: actions/upload-artifact@v4
        with:
          name: armorindicator
          path: project/build/libs/*.jar
